shardlab/discordrb

lib/discordrb/api.rb

fix: only specify ratelimit precision if required

---

lib/discordrb.rb

Add a helper to create formatted timestamps.
---
- `Discordrb.timestamp`
- `Discordrb::TIMESTAMP_STYLES`

feat: Add timestamp formatting helper

---

lib/discordrb/data/interaction.rb

Adds `number` option for application commands.
Adds `min_value` and `max_value` options for numeric parameters.
---
`OptionBuilder#number`
Added `max_value` and `min_value` to numeric options.

feat: Add number and numeric options

---

lib/discordrb/api.rb
lib/discordrb/api/channel.rb
lib/discordrb/bot.rb
lib/discordrb/cache.rb
lib/discordrb/commands/container.rb
lib/discordrb/commands/rate_limiter.rb
lib/discordrb/container.rb
lib/discordrb/data/channel.rb
lib/discordrb/errors.rb
lib/discordrb/events/threads.rb
lib/discordrb/gateway.rb
lib/discordrb/voice/sodium.rb
spec/permissions_spec.rb

feat: Threads

---

lib/discordrb/data/interaction.rb

Add the missing components parameter in [edit_response](https://drb.shardlab.dev/main/Discordrb/Events/InteractionCreateEvent.html#edit_response-instance_method) doc.
---
components parameter in [edit_response](https://drb.shardlab.dev/main/Discordrb/Events/InteractionCreateEvent.html#edit_response-instance_method) doc

Add components parameter in edit_response doc

---

lib/discordrb/data/audit_logs.rb

- Don't `#to_sym` type in audit log processing

fix: update audit log processing

---

lib/discordrb/data/interaction.rb

This PR aims to allow `.mention` on an ApplicationCommand
---
~Added the method `.mention` with the alias `.to_s`
~The ability to mention slash commands

Add support for slash command mentions

---

lib/discordrb/data/user.rb
spec/api/channel_spec.rb

Expose user flags
- User#staff?
- User#partner?
- User#hypesquad?
- User#bug_hunter_level_1?
- User#hypesquad_online_house_1?
- User#hypesquad_online_house_2?
- User#hypesquad_online_house_3?
- User#premium_early_supporter?
- User#team_pseudo_user?
- User#bug_hunter_level_2?
- User#verified_bot?
- User#verified_developer?
- User#certified_moderator?
- User#bot_http_interactions?
- User#public_flags

feat: add user badges

---

lib/discordrb/data/message.rb

This PR adds the ability to check whether a message was an application command response AND adds the ability to check the type of a message.
---
~ `#type` for messages which returns the type of a message(returns integer)
~̶ ̶`̶#̶a̶p̶p̶l̶i̶c̶a̶t̶i̶o̶n̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶s̶p̶o̶n̶s̶e̶?̶`̶ ̶w̶i̶t̶h̶ ̶a̶l̶i̶a̶s̶e̶s̶ ̶`̶#̶s̶l̶a̶s̶h̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶s̶p̶o̶n̶s̶e̶?̶`̶,̶ ̶`̶#̶s̶l̶a̶s̶h̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶p̶l̶y̶?̶`̶,̶ ̶a̶n̶d̶ ̶`̶#̶a̶p̶p̶l̶i̶c̶a̶t̶i̶o̶n̶_̶c̶o̶m̶m̶a̶n̶d̶_̶r̶e̶p̶l̶y̶?̶`̶ ̶T̶h̶i̶s̶ ̶m̶e̶t̶h̶o̶d̶ ̶r̶e̶t̶u̶r̶n̶s̶ ̶a̶ ̶b̶o̶o̶l̶e̶a̶n̶ ̶s̶i̶g̶n̶i̶f̶y̶i̶n̶g̶ ̶w̶h̶e̶t̶h̶e̶r̶ ̶a̶ ̶m̶e̶s̶s̶a̶g̶e̶ ̶w̶a̶s̶ ̶a̶ ̶s̶l̶a̶s̶h̶ ̶c̶o̶m̶m̶a̶n̶d̶ ̶r̶e̶s̶p̶o̶n̶s̶e̶ ̶o̶r̶ ̶n̶o̶t̶ (changed to below:)
~`#chat_input_command?` ~~with alias `#application_command_response?`~~ This method returns a …

#application_command_response and #type for message

---

LICENSE.txt

The year for the licensing hasn't been updated since 2020, this PR updates it
~LICENSE.txt now says `Copyright (c) 2015-2022` instead of `Copyright (c) 2015-2020`

Update year for LICENSE.txt

---

lib/discordrb/webhooks/view.rb

https://discord.com/developers/docs/interactions/message-components#select-menu-object

Add "disabled" attribute for the select menu builder

---

lib/discordrb/api/application.rb
lib/discordrb/bot.rb
lib/discordrb/data/interaction.rb

This PR adds support for application command localizations 
https://discord.com/developers/docs/interactions/application-commands#localization
~The LocalizationBuilder class
~The `.guild_locale`(with aliases `.server_locale` `.server_language` and `.guild_language`) and `.locale`(with alias `.language`) methods for interactions
~Support for creating application commands with localized names and descriptions
[locale-ex (2).txt](https://github.com/shardlab/discordrb/files/11067203/locale-ex.2.txt) This .txt file demonstrates how to register localizations and check the selected language of the invoking user

Add Localization Support

---

lib/discordrb/api/application.rb
lib/discordrb/bot.rb
lib/discordrb/data/interaction.rb

Reverts shardlab/discordrb#190 as per discussion on discord api [here](https://discord.com/channels/81384788765712384/381891448884428801/1089954006622814379)

Revert "Add Localization Support"

---

lib/discordrb/bot.rb

Resolves issues with Threads Events that have been reported on the Discord
By the way, solves issue #186, and closes pull request #187
---
- Resolves issues with Threads Events that have been reported on the Discord
> `lib/discordrb/bot.rb`

Fix Threads Events

---

CHANGELOG.md
discordrb.gemspec
lib/discordrb/version.rb
lib/discordrb/webhooks/version.rb

feat: version bump

---

lib/discordrb/api/channel.rb
lib/discordrb/data/message.rb

Add crossposting messages in a news channel.
`Message#crosspost`
`API::Channel.crosspost_message`

Add crossposts.

---

lib/discordrb/bot.rb
lib/discordrb/data/activity.rb
lib/discordrb/data/server.rb
lib/discordrb/data/user.rb
lib/discordrb/gateway.rb
lib/discordrb/permissions.rb

- corrected new cop suggestions for Style/BitwisePredicate

chore: rubocop Style/BitwisePredicate

---

lib/discordrb/data/channel.rb

Fix for https://github.com/shardlab/discordrb/issues/238

Fix permission overwrites mapping

---

lib/discordrb/data/message.rb

Lazily request message authors to avoid request spam on history requests with members that are no longer in the server.
---
Author information is now populated lazily if not in a DM or the author is not a webhook

fix: lazily request author for messages

---

lib/discordrb/api/application.rb
lib/discordrb/bot.rb
lib/discordrb/data/interaction.rb

This PR adds support for setting the NSFW field on application commands
`nsfw` parameter when creating or updating an application commands

feat: NSFW
