lib/discordrb/bot.rb
`Bot#send_temporary_message` was missing the message reference field. Closes https://github.com/discordrb/discordrb/issues/749
`Bot#send_temporary_message` - add `message_reference` argument.
=> Fixup Bot#send_temporary_message; missing message_reference

lib/discordrb/bot.rb, lib/discordrb/data/activity.rb
Add support for `Competing` activity type to `Activity` and `Bot`. Fixes #14.
---
* `Activity::COMPETING`, `ActivitySet#competing`
* `Bot#competing=` to set the competing status
* Updated comments to add Competing to the list of activity types
=> Add Competing to activity types

lib/discordrb/data/invite.rb
Left in a bad conditional check in the Invite initializer
`Invite#initialize`
=> fixup: remove bad conditional in Invite initializer

lib/discordrb/api/channel.rb, lib/discordrb/api/server.rb, lib/discordrb/api/user.rb
Re: #7, add missing links to Discord API documentation for methods in `lib/discordrb/api/*.rb`.
---
Links to API documentation for API request methods.
=> Add doc links to API methods

lib/discordrb/commands/command_bot.rb, spec/commands_spec.rb
Reopens https://github.com/discordrb/discordrb/pull/750 as per @swarley and fixes rubocop violations.
Allows the `CommandBot` `command_doesnt_exist_message:` to be a callable. The behaviour stays the same for existing strings and `nil` passed in, but if instead something that responds to `:call` is passed in, that is first called with the `event`, then the result handled in the same way as above. This includes the `nil` behaviour and the replacing of the `"%command%"` substring.
Example:
```ruby
bot = Discordrb::Commands::CommandBot.new(
token: token,
prefix: "!",
command_doesnt_exist_message: ->(event) {
"Your command %command% doesn't exist. Have you tried? #{ find_similar_commands(event) }"
}
)
```
* `CommandBot` `command_doesnt_exist_message:` can be be a callable.
The other approach …
=> Pass a callable into CommandBot command_doesnt_exist_message:

lib/discordrb/data/message.rb, spec/data/message_spec.rb
`@server` would be nil if `guild_id` wasn't in the payload, despite the channel belonging to a guild.
- `Message#initialize`
=> Fixup message link

discordrb-webhooks.gemspec, discordrb.gemspec, lib/discordrb/version.rb, lib/discordrb/webhooks/version.rb
When the both webhooks and the main library were updated to 3.4.0, the gemspec pointing to webhooks from main was left on 3.3.0.
3.3.0 used `rest-client >= 2.1.0.rc1` which was reverted here https://github.com/shardlab/discordrb/commit/648596335da886b01ed87ff6f43c8bc2a7e0aae4
This causes incompatibilities when using rest-client 2.0.x in other gems.
=> Update webhooks gemspec to match

lib/discordrb/errors.rb
Many discord errors don't have an `"errors": {}` object and only have a message such as `"message": "404: Not Found"`.
This change sets stops calling `flatten_errors` and sets `@errors` to be `[]` in the case of no errors object as 404's and other auth errors are currently throwing a further exception when doing `errors.collect`.
=> Fix lack of errors to flatten

spec/commands_spec.rb
Fix test for positional arguments and keyword arguments separation for Ruby 3.0.
See more about keyword arguments behaviour: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
```shell
rbenv local 3.0.0 
gem i bundler
bundle install
bundle exec rspec
```
`spec/commands_spec.rb`
=> Fix test for Ruby 3.0

lib/discordrb/data/member.rb
Provides convenience methods for banning/unbanning/kicking Members directly instead of having to go through Server. 
Resolves #45
**Current:**
```rb
member.server.ban(member, reason: 'bonk')
```
**New:**
```rb
member.ban(reason: 'bonk')
```
`Member#ban`
`Member#unban`
`Member#kick`
=> Add ban/unban/kick directly to Member

lib/discordrb/bot.rb
Presence update events attempted to pull old information from users that were uncached.
=> Do not assume users are cached in presence update

lib/discordrb/data/message.rb
New Message methods that add an await for a `ReactionAddEvent` for that message.
Fixes #30 
---
- `Message#await_reaction`, `Message#await_reaction!`
=> Add reaction awaits to Message

lib/discordrb/api/channel.rb, spec/api/channel_spec.rb, spec/data/message_spec.rb
Fixes #38.  
Discord tries to parse the `limit` parameter as an integer, if nothing is sent a HTTP 400 is returned. This sets a default to the maximum instead of the usual 25, to reduce the number of requests needed to get all users when `limit: nil` is passed.
---
Specs for `Message#reacted_with` and `API::Channel.get_reactions`
* API::Channel.get_reactions: the query param `limit` defaults to 100 instead of the empty string when limit is nil.
=> Don't send an empty limit query parameter for Channel#get_channel

lib/discordrb/api/webhook.rb, lib/discordrb/data/webhook.rb, lib/discordrb/errors.rb, lib/discordrb/webhooks/builder.rb, lib/discordrb/webhooks/client.rb, spec/data/webhook_spec.rb, spec/webhooks_spec.rb
Adds support for editing and deleting webhook messages. Also adds execute support to API and Webhook objects that have tokens associated with them.
---
`Webhook#execute` - Now allows execution of webhooks retrieved via the API (with some stipulations).
`Webhook#delete_message`
`Webhook#edit_message`
`API::Webhook.token_execute_webhook`
`API::Webhook.token_edit_message`
`API::Webhook.token_delete_message`
`Webhooks::Builder#allowed_mentions`
`Webhooks::Builder#allowed_mentions=`
`Webhooks::Client#edit_message`
`Webhooks::Client#delete_message`
`Webhooks::Client#delete` - Delete a webhook via a client
`Webhooks::Client#modify` - Modify webhook properties via a client
`Errors::UnauthorizedWebhook` - Error raised when attempting to use `execute`, `delete_message`, or `edit_message` on an API …
=> Webhook update

lib/discordrb/data/message.rb
#3 added support for inline replies, which is fantastic, but it seems the documentation for `Message#reply!` was accidentally copied over from `Channel#send_message`. This patch updates that documentation.
I debated putting _inline reply_ in quotation marks since as far as I can find it's not an official term in [the API](https://discord.com/developers/docs/resources/channel#message-object) (an inline reply is simply referred to as "a reply"), but decided it only made the sentence more confusing.
---
Incorrect description for `Message#reply!`
=> Update documentation for Message#reply!

lib/discordrb/data/message.rb
Use the correct arguments when creating a member from message data.
Fixes #56.
`Discordrb::Message#initialize` - Add server argument to initializer call.
=> fixup: Add server arg when creating member in Message#initialize

lib/discordrb/api.rb
429s were being consumed as coded Discord errors and not being properly re-raised.
---
`Discordrb::API.request` - Do not parse 429s as code errors.
=> bugfix: Do not parse 429s as a code error

lib/discordrb/data/interaction.rb
Adds support for button interactions.
* Exposes `Interaction#data` which provides the `custom_id` of the clicked button.
* Adds `Interaction#button`, a convenience method for retrieving the selected button by its `custom_id`. This is useful for obtaining the label of the clicked button.
* Adds `Interaction::COMPONENT_TYPES`
* Adds the new button type to `Interaction::TYPES`
=> Add support for button interactions

lib/discordrb/data/member.rb
Resolves an issue where Presence events provide member objects without the `roles` key.
```
[IN : websocket @ 2021-06-09 21:33:21.774] {"t"=>"PRESENCE_UPDATE", "s"=>9, "op"=>0, "d"=>{"user"=>{"username"=>"REDACTED", "id"=>"123", "discriminator"=>"1234", "avatar"=>"aaa"}, "status"=>"online", "guild_id"=>"2345", "client_status"=>{"mobile"=>"online"}, "activities"=>[]}}
[ERROR : websocket @ 2021-06-09 21:33:21.774] Gateway message error!
[ERROR : websocket @ 2021-06-09 21:33:21.775] Exception: #<NoMethodError: undefined method `map' for nil:NilClass>
[ERROR : websocket @ 2021-06-09 21:33:21.776] .../lib/discordrb/data/member.rb:69:in `initialize'
```
Uses safe navigation to map the role IDs, defaulting to an empty array.
=> Fix Member role_ids

lib/discordrb/permissions.rb, spec/permissions_spec.rb
This PR gets us up to date with the [new permissions](https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags).
It also adds a helper method to get all the permissions a Permission object has.
```ruby
Discordrb::Permissions.new(9).defined_permissions
=> [:create_instant_invite, :administrator] 
Discordrb::Permissions.new(2425372770).defined_permissions
=> [:kick_members, :manage_server, :add_reactions, :embed_links, :connect, :deafen_members, :manage_roles, :use_slash_commands]
```
---
`Permissions#defined_permissions` to get an array of symbols of the permissions.
- Added 31-36 permission fields, these being:
```ruby
31 => :use_slash_commands,   # 2147483648
32 => :request_to_speak,     # 4294967296
33 => :manage_threads,       # 8589934592
34 => …
```
=> Update permissions and add Permissions#defined_permissions

lib/discordrb/api/channel.rb
`API::Channel.edit_message` was not set up to receive components from e.g. `Message#edit`. This PR adds that missing parameter so message edits function.
Fixes #72.
---
- missing components parameter in `edit_message`
=> Bugfix: handle components when editing message

examples/slash_commands.rb
I thought I already made a PR for this lol
It's just a typo fix, thats all this is.
I only noticed this using this example file to get an idea of how this api works
---
+ Singular letter into a comment
Slash_Commands.rb
A singular typo :P
=> Fix typo in slash commands

lib/discordrb/webhooks/builder.rb
Fixup bad logic that caused 400s when using an allowed mentions builder in webhooks.
`Webhooks::Builder#to_json_hash` - Call `to_hash` on allowed mentions
`Webhooks::Builder#to_multipart_hash` - Call `to_hash` on allowed mentions
Closes #81
=> fix(Webhooks): Convert allowed_mentions to hash before execute

lib/discordrb/data/interaction.rb
Fixes #77
- Fixed the type check to look for the component interaction type
- Returning a button constructed within an `ActionRow` instead of constructing it from the top-level data. This is necessary because the top-level data does not contain button-specific fields like label and style.
- Corrected the documented type of `Interaction#data`
=> Fix Interaction#button

lib/discordrb.rb, lib/discordrb/bot.rb, lib/discordrb/commands/command_bot.rb
With v8, intents are enforced when identifying. By default the library will request all intents, including privileged ones, even if the bot does not use them. This PR makes it easier for the authors of such bots to only request unprivileged intents as opposed to all intents.
It also allows you to specify _no_ intents. Previously the documentation suggested that you could use `nil` for this, but this would have caused an error.
---
`Discordrb::UNPRIVILEGED_INTENTS`
`Discordrb::NO_INTENTS`
`Bot#initialize`: `intents` can now be equal to `:unprivileged`
`Bot#initialize`: `intents` can now be equal to `:none`
=> Allow Bot#initialize to request only unprivileged intents

lib/discordrb/data/server.rb, lib/discordrb/gateway.rb
Fixes #51.
The gateway doesn't respond if we try to ask for server members without first declaring the intent. Originally, `Server#members` would just wait for a response that isn't coming, causing it to never return. This change checks the intents we sent with the gateway first before requesting members.
---
- Exposed `Gateway#intents`, the final calculated intents parameter sent to the gateway
- `Server#members` now raises a RuntimeError if the gateway was not initialized with the SERVER_MEMBERS intent
=> Check if we have the SERVER_MEMBERS intent before fetching server members

lib/discordrb/data/channel.rb
Ensures the `message_id` parameter of `Channel#load_message` is not nil since we cannot load the message without it. Calling the method with a nil value will now return a more helpful `ArgumentError` instead of a `Discordrb::Errors::UnknownError`.
Added a check to `Channel#load_message` to ensure the `message_id` parameter is not nil.
```rb
bot.channel(12345).message(nil)
[ERROR : main @ 2021-08-13 17:40:53.860] 404: Not Found
Discordrb::Errors::UnknownError: 404: Not Found
```
```rb
bot.channel(12345).message(nil)
ArgumentError: message_id cannot be nil
```
=> Require message_id for Channel#load_message

lib/discordrb/data/message.rb, spec/data/message_spec.rb
Fixes sending a limit over 100 as this is an error for the API requests
The Paginator object handles limits.
The API method handles limit defaults.
When you send Message#reacted_with with a limit over 100, it will pass this to the API method and fail.
---
Message#reacted_with now accepts limits over 100
=> Fixup: Paginate reactions

lib/discordrb/data/message.rb, spec/data/message_spec.rb
Making my discord bot obtain a list of users who reacted to a message was a bit unintuitive at first. Then I noticed the open issue #37 related to adding new functionality to reactions and decided to tackle this issue so that my bots and others like it can take advantage of the new workflows. 
Lets say you're hosting a giveaway and want people to enter for different prize pools 🟥 and 🟢 based on their reaction:
`giveaway_message.all_reaction_users`
`=> { '🟥' => [<User bob>, <User jack>], '🟢' => [<User bob>, <User jane>] }`
Additionally, it is no longer required to resolve a reaction to a string to use it with `Message#reacted_with`:
`giveaway_message.reacted_with(<Reaction 🟥>, limit:100)`
`=> [<User bob>, <User jack>]`
Resolves #37 
---
- Implemented `Message#all_reaction_users` which …
=> Issue #37 resolution: New Reaction Workflows

lib/discordrb/data/message.rb, spec/data/message_spec.rb
Fix `reacted_with` specs and prevent additional API calls when paginating.
`Message#reacted_with` - If limit can fit in a single page, do not use a paginator, otherwise return as soon as a page is not full.
=> fix: Correct reacted_with spec and prevent extra API call.

lib/discordrb/bot.rb
Slash command execution previously blocked the main thread, this makes them run in a per event thread and adds a small amount of debug logging.
---
- Make `ApplicatoinCommandEvent` dispatch multi-threaded.
Closes #88.
=> fix(Interactions): make slash command execution async

lib/discordrb/data/component.rb, lib/discordrb/data/interaction.rb
I assume that rails isn't playing nicely with the use of `to_json` in `Discordrb::Components::View`. This refactors away to `to_a` directly to avoid it all together.
---
No public API changes.
=> fix: Use to_a to avoid rails problems

lib/discordrb/cache.rb
We currently have an internal blacklist setup to prevent accessing a channel we don't have permission to see, but we never purge this cache so it's becoming an issue.
In the future it may be desirable to dynamically track this through every event associated with channel visibility (there are many). However for the time being removing this check entirely is the best course of action.
---
`Cache#channel` - No longer maintains a cache of channels that have returned a 403
=> feat!: Remove restricted channels check

lib/discordrb/bot.rb, lib/discordrb/data/server.rb, lib/discordrb/gateway.rb
This changes chunking calculation to use the discord provided `chunk_index` and `chunk_count` fields instead of checking for expected length. This should help us avoid some difficult to trace deadlocks.
---
`Server#process_chunk` - now accepts an additional two arguments; `chunk_index` and `chunk_count`.
=> refactor: Use chunk_index and chunk_count to determine chunk status.

lib/discordrb/bot.rb, lib/discordrb/cache.rb, lib/discordrb/data/server.rb
Adds an option to `ensure_server` to force the recache of a guild. This is necessary because there is a window in this cache lifecycle where we can have a server object with bad state that permanently occupies the cache.
- `Cache#ensure_server` - Add `force_recache` parameter to ensure guilds from `GUILD_CREATE` are used as the source of truth.
- `Server#update_data` - Move data initialization logic from `initialize` to `update_data` for reusability.
=> fix: force guild recache from GUILD_CREATE

lib/discordrb/cache.rb, lib/discordrb/data/channel.rb
When migrating to v8 we bubbled up better-formatted errors based on the code provided from discord. Our cache methods were still rescuing from rest-client scoped errors instead of the discord equivalents.
---
Rescue from `Discordrb::Errors::Unknown*` instead of `RestClient::ResourceNotFound`
- `Channel#load_message`
- `Cache#user`
- `Cache#member`
- `Cache#channel`
=> fix: rescue from internal errors instead of rest-client

lib/discordrb/bot.rb, lib/discordrb/data/interaction.rb
Adds a builder for declaring permissions when creating or editing a slash command.
---
Interactions::PermissionBuilder
Bot#register_application_command and Bot#edit_application_command now yield PermissionBuilders
=> feat: Add application command permission builder

lib/discordrb/bot.rb
Added public method for fetching all application commands.
```ruby
bot.get_application_commands # => Array<ApplicationCommand>
bot.get_application_commands(server_id: SAMPLE_SERVER_ID) # => Array<ApplicationCommand>
```
---
- `Discordrb::Bot#get_application_commands`
=> Add method for fetching all application commands

lib/discordrb/api.rb
The `retry_after` response returned with a 429 is in seconds [according to the documentation](https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit) and so is the `sleep` time. We shouldn't be converting it to milliseconds. This PR mimics what the `handle_preemptive_rl` method does for `X-RateLimit-Reset-After` which is also in seconds.
I don't know how to reproduce this yet, but it happened twice today and generated hundreds of thousands of retry requests milliseconds apart because the sleep was essentially 0. We had to reboot the server to stop it. Here is what that looked like in our Honeycomb.io monitoring dashboard:
We've added some more instrumentation to see the RestClient response headers so if it happens again, maybe we can get a better idea of what is …
=> fix: 429 runaway retry. `retry_after` is in seconds and so is `sleep`

lib/discordrb/api/server.rb, lib/discordrb/bot.rb, lib/discordrb/commands/container.rb, lib/discordrb/commands/rate_limiter.rb, lib/discordrb/container.rb, lib/discordrb/data/member.rb, lib/discordrb/errors.rb, spec/permissions_spec.rb
Support new discord timeouts feature.
---
Adds `Member#communication_disabled_until`, `Member#communication_disabled_until=`, and `Member#communication_disabled?`. Also corresponding aliases using `timeout` terminology.
=> feat: Support timeouts

lib/discordrb/api.rb
In the case of a 429 after an API ban, the retry-after in the JSON body isn't present, but is present in the headers.
The library will incorrectly wait for 0.0s since it's `nil` in the body and spam the API. This fixes this issue.
Use retry-after response header if retry-after is missing in the response body
=> fix: Use retry-after response header if missing in the response body for 429 API bans

lib/discordrb/data/member.rb
aae1366 broke role operations by failing to determine role IDs assuming that they may be updated and added to the role variable but not the role ids variable. This adds a method to determine the appropriate way to determine role IDs depending on if the roles array if populated or not.
Fixes #118.
--------
`Member#resolve_role_ids` - Pull role IDs from roles or role_ids based on presence.
`Member#add_role`
`Member#remove_role`
`Member#modify_roles`
=> fix: Use roles to determine ids when present

lib/discordrb/data/interaction.rb
Embeds passed as parameters to interaction methods were not properly serialized. This PR unifies builder preparation to ensure the embed builder is responsible for creating the payload.
---
`Interaction#prepare_builder` - private method for adding information passed as parameters.
Interaction methods all serialize embeds passed via parameters properly.
=> fix(Interaction): serialize embeds in respond

lib/discordrb/data/interaction.rb
ApplicationCommand server ID was being incorrectly serialized as 0 when no ID was given.
- `nil` server IDs are now stored correctly on ApplicationCommands
=> fix(ApplicationCommand): prevent nil into 0 for server_id

lib/discordrb/data/interaction.rb, lib/discordrb/events/interactions.rb
I'm not sure why, but I previously was overwriting the message author with the person who invoked the interaction.
This doesn't really make any sense to do so it's been removed.
---
- `Interaction#user` is now documented to also return a Member object for guild based interactions.
- `InteractionCreateEvent` no longer overwrites the data from the interaction.
=> fix(InteractionCreate): dont override user for interactions

lib/discordrb/data/interaction.rb
Expose a components reader on interaction message.
---
`Interactions::Message#components`
=> fix: expose components in interaction message

lib/discordrb/data/component.rb
Correct component typo in action row.
---
`ActionRow#components`
=> fix: correct component typo

.circleci/config.yml, README.md, discordrb-webhooks.gemspec, discordrb.gemspec, lib/discordrb/data/user.rb, lib/discordrb/events/interactions.rb, spec/overwrite_spec.rb
Ruby 2.6 EOLs at the end of March, so this should be the last of my RuboCop/dependency/general hedge-trimming PRs to target 2.6. Future PRs of this nature will be from my Ruby 2.7-based branch.
Changes are minimal here; the main change that should be noted is the [opt-in to requiring MFA for privileged operations on RubyGems](https://guides.rubygems.org/mfa-requirement-opt-in/).
---
- Added Ruby 3.1 to the CI test matrix.
- Updated dependencies (RuboCop, RSpec) and applied new RuboCop suggestions.
- Added MFA requirement for RubyGems.
=> Dependency Bumps, Test Matrix Update

lib/discordrb/api/channel.rb
Bots aren't allowed in group DMs, and while the [API docs](https://discord.com/developers/docs/resources/channel#group-dm-add-recipient) list a bunch of methods for managing group DMs, they aren't meant for bots to use, and don't work as currently implemented.
The API methods are meant to be used by the (deprecated) GameBridge SDK to invite people to a temporary "room" on Discord, relying on each party authenticating with an OAuth application separately.
Fixes #16 
---
`Discordrb::API::Channel`
* `.create_empty_group`
* `.create_group`
* `.add_group_user`
* `.remove_group_user`
* `.leave_group`
=> Deprecate group DM endpoint methods

.circleci/config.yml
As noted in #136 CircleCI is deprecating its 14.04/16.04 images. This PR resolves #136 by switching to a Docker executor in the docs deploy step, where we were previously using the default `machine` executor.
---
- Switch to Docker executor in CI for docs deploy step
=> Use Docker executor in CI for deploying docs

lib/discordrb/api/channel.rb, spec/api/channel_spec.rb
Added support of method https://discord.com/developers/docs/resources/channel#delete-all-reactions-for-emoji in `Discordrb::API::Channel`. Fixed #158 
Added `Discordrb::API::Channel.delete_all_emoji_reactions` method. Added basic test case.
=> Added support of deleting all reactions for emoji in Channel

lib/discordrb/errors.rb
Fixed compatibility of `Discordrb::Errors::CodeError#full_message` with IRB for Ruby > 3.0. Fixed #163 
---
Added unused args to `#full_messages`.
=> Fixed compatibility of full_messages for Ruby 3.0

lib/discordrb/gateway.rb
As of June 27, the $ prefix in the identify connection properties is deprecated. This PR removes the prefix to prepare for the deprecation.
---
~Removed the '$' prefix in the identify connection properties. Ex. 
Old: `'$browser': 'discordrb'`
New: `browser: 'discordrb'`
Deprecated features from gateway.rb
=> Prepare for discord deprecations

lib/discordrb/data/channel.rb
There are three channel types not currently represented in the gem, although I guess it may not be worth adding these values if we don't support their corresponding functionality in the gem?
Also, not sure if forum (15) should be included since it's in active development.
See https://discord.com/developers/docs/resources/channel#channel-object-channel-types
---
- Added the newest channel types to the TYPES hash in Discordrb::Channel:
- `GUILD_STAGE_VOICE` as `stage_voice`
- `GUILD_DIRECTORY` as `directory`
- `GUILD_FORUM` as `forum`
=> Add new channel types.

examples/modals.rb, lib/discordrb/api/interaction.rb, lib/discordrb/bot.rb, lib/discordrb/container.rb, lib/discordrb/data/component.rb, lib/discordrb/data/interaction.rb, lib/discordrb/events/interactions.rb, lib/discordrb/webhooks.rb, lib/discordrb/webhooks/modal.rb
Add modal functionality.
---
- Discordrb::Webhooks::Modal - Modal builder for interactions
- Discordrb::EventContainer#modal_submit - Register a handler for modal submit
- Discordrb::Events::ModalSubmitEvent
- Discordrb::Events::ModalSubmitEventHandler
- Discordrb::API::Interactions.create_modal_interaction_response
- Discordrb::Interaction#get_component - Retrieve a component from an interaction via custom_id
=> feat: add modals

lib/discordrb/api.rb, lib/discordrb/api/server.rb, lib/discordrb/data/role.rb
Add role icons
---
- Discordrb::API::role_icon_url
- Discordrb::Role#icon
- Discordrb::Role#icon_url
- Discordrb::Role#icon=
- Added icon parameter to role update
=> feat: add role icons

spec/api/channel_spec.rb
Fixed failed test after merging #161. Retested in playground with my server, rubocop & rspec - 👌 
Updated `emoji` attributes in test case.
=> Fixed Discordrb::API::Channel.delete_all_emoji_reactions spec

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .markdownlint.json, CHANGELOG.md, README.md
I had noticed that there was a lot of inconsistency of style in our Markdown files. Not a big deal, but I also wanted to fix a few small issues I'd noticed, so it was easy to just wrap all the changes up together.
If y'all think my moving the README badges from the top to just under the h1 is dumb, I'll yeet that commit and re-push.
---
- Made style and formatting in Markdown files consistent using Prettier and markdownlint.
- Use https in inch-ci badge link.
- Fixed link to v3.4.2 tag in the changelog.
- Fixed improperly formatted ISO 8601 dates in changelog.
=> Minor fixes and making style consistent in Markdown files

lib/discordrb/data/channel.rb, spec/api/channel_spec.rb
In order to match the official API, the maximum value is increased from 120 to 21600
Issue #175
=> Modification of the maximum value of rate_limit_per_user

.circleci/config.yml, .rubocop.yml, README.md, discordrb-webhooks.gemspec, discordrb.gemspec, examples/slash_commands.rb, lib/discordrb.rb, lib/discordrb/data/channel.rb, lib/discordrb/permissions.rb
Ruby 2.6 is EOL. This PR bumps our minimum Ruby support to >= 2.7 and performs all the usual dependency chores (version bumps, application of new cops). Also fixed a small issue with CI test result storage introduced because #140 didn't integrate the changes from #95. 
---
- Dropped support for Ruby 2.6.
- CI test results for Ruby 3.1 are stored like the other versions.
- Applied new cops.
=> Ruby 2.6 EOL and Dependency Chores

lib/discordrb/data/interaction.rb, lib/discordrb/data/message.rb
This would create a shortcut to using all of the methods that are available for Discordrb::Message
- Added Interactions::Message#to_message (2c87b416a89efd2c705fbe20bd81128fe22dfa6d)
- Added to_message to Discordrb::Message (0970ff27c2a70b26e0092af3fafff107651aae86)
Adding to_message to Discordrb::Message was in inspiration of Ruby's String#to_s method.
=> Add to_message to Interactions::Message

lib/discordrb/data/server.rb
`Server#max_emoji` has typo in it by referring to `@level` instead of `@boost_level` attribute, hence it returns `50` every time.
- Replaced `@level` with correct `@boost_level`
=> fix: Server#max_emoji returning wrong value

lib/discordrb/data/invite.rb
Use `ensure_user` to avoid making an API call during invite creation.
=> feat: optimize user caching for invites

.circleci/config.yml
In order to allow the "pages" task to be able to clone the repository again, it is necessary to update the fingerprint of the RSA SSH host key of Github.com which has changed since March 24th
This fingerprint is available directly in the attached article:
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
---
RSA SSH host key fingerprint of Github.com in .circleci/config.yml
=> Update of the RSA SSH fingerprint of Github.com

examples/select_menus.rb, lib/discordrb/webhooks/view.rb
Kwarg forgotten in string_select method probably during the last rebases.
And adding disabled attributes that were not put on the new components during the last rebases.
Fix PR #213
---
- Adding disabled attributes that were not put on the new components during the last rebases
- Kwarg forgotten in string_select method
=> Bugfix - Kwarg forgotten in string_select method

lib/discordrb/data/attachment.rb, lib/discordrb/data/interaction.rb, lib/discordrb/events/interactions.rb
This pull request adds support of `attachment` option type to Interactions.
Also adds missing [attributes](https://discord.com/developers/docs/resources/channel#attachment-object) to Attachment class.
- add `attachment` type to option types and builder;
- resolve attachments objects so they can be accessed within interaction;
- add `description`, `content_type` and `ephemeral` (w/ `ephemeral?` alias) attributes to Attachment class.
```rb
bot.register_application_command(:test, "get info about attachment", server_id: SERVER_ID) do |cmd|
cmd.attachment("file", "test file", required: true)
end
bot.application_command(:test) do |event|
file = event.resolved.attachments[event.options["file"].to_i]
event.respond do |msg|
msg.add_embed do |embed|
embed.description = <<~MSG
id: #{file.id} …
```
=> Feature: Support attachment option type

lib/discordrb/data/server.rb
It's all in the title
Allows to fix issue #185 
---
- Server#move accept nil for channel param
=> Allow disconnect user from a voice channel via the Server#move method

lib/discordrb/bot.rb
This fixes a bug where thread channels aren't deleted.
`channel_delete` is a method call to register an event handler. As a block was not passed to this call, whenever a channel is then deleted it would raise a NoMethod error to call for nil.
- Threads are now deleted from the cache correctly
- Empty channel delete handlers are no longer created on thread deletion
=> Fix thread delete method call

lib/discordrb/data/role.rb
I added a wrapper class for the Discord role's tags and added the tags field to the role model as it wasn't possible to access the role tags data (e.g. role's bot ID) while using the server role created/updated/deleted gateway event payload.
---
- added `Discordrb::Role::Tags` class
- added `Discordrb::Role#tags` attribute
=> Add tags to role model

lib/discordrb/bot.rb
At the moment `Bot#invite_url` doesn't allow to pass bot scopes and redirect uri to invite url. This PR adds ability to pass them with other options.
---
```rb
bot = Discordrb::Bot.new token: 'token'
bot.ready do
puts bot.invite_url(redirect_uri: 'https://example.com/callback', scopes: %w[bot applications.commands])
end
```
Replaced string interpolation with `URI.encode_www_form({ }.compact)`
=> feat: Bot#invite_url - scope & redirect_uri params

lib/discordrb/webhooks/client.rb, spec/webhooks_spec.rb
discordrb uses API v9 but the generated webhook URLs use API v8. This PR updates webhook URLs to v9 for consistency. Webhooks don't get breaking changes anyway
updated webhook URLs from v8 to v9
=> Update webhook URLs to v9

lib/discordrb/api/application.rb, lib/discordrb/bot.rb
Add default_member_permissions and contexts field to application commands to allow disabling of application commands in DMs and more precise setting of permissions. 
---
- Added default_member_permissions and contexts to register_application_command and edit_application_command
- Added default_member_permissions and contexts to create_guild_command, create_global_command, edit_guild_command and edit_global_command. 
Nothing yet, although I'd recommend removing/deprecating default_permission in favour of default_member_permissions. I could incorporate this in my PR if desired, but we can also decide to keep this for now.
- Implement fix as suggested by #253
=> Add default_member_permissions and contexts fields to application commands

lib/discordrb/data/interaction.rb
Add missing supported arguments for string and integer option types
* `string` - add support for `min_length` & `max_length` arguments
* `integer` - add support for `min_value` & `max_value` arguments
* `number` - add documentation for `min_value` & `max_value` arguments
```rb
BOT.register_application_command(:test, "test command") do |cmd|
cmd.integer("integer", "integer option", required: false, min_value: -5, max_value: 5)
cmd.number("number", "number option", required: false, min_value: -3.14, max_value: 3.14)
cmd.string("string", "string option", required: false, min_length: 8, max_length: 32)
end
BOT.application_command(:test) do |event|
integer = event.options["integer"]
number = event.options["number"]
string = event.options["string"]
event.respond(ephemeral: true) do |msg| …
```
=> add min/max_length support for string option and min/max_value for integer

discordrb.gemspec, lib/discordrb/api/server.rb, lib/discordrb/data/overwrite.rb, lib/discordrb/data/server.rb, lib/discordrb/permissions.rb
Adds the [search guild members endpoint](https://discord.com/developers/docs/resources/guild#list-guild-members) and a corresponding abstraction for the server object.
`#search_guild_members` API call.
`#search_members` method.
Fixes the following warning by adding Base64 as an explicit dependency.
```
ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/data.rb:18: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of discordrb-3.5.0 to add base64 into its gemspec.
```
=> Feat: search guild members

lib/discordrb/api/channel.rb, lib/discordrb/bot.rb, lib/discordrb/data/activity.rb, lib/discordrb/data/message.rb, lib/discordrb/data/server.rb, lib/discordrb/data/user.rb, lib/discordrb/gateway.rb, lib/discordrb/permissions.rb, spec/data/message_spec.rb
* Add `pry-byebug` to development dependencies
* Add `API::Channel#suppress_embeds`
* Add `Message#suppress_embeds`
=> Allow supressing embeds on Message

lib/discordrb/commands/command_bot.rb, lib/discordrb/data/message.rb
Adds support for accessing the thread started from a message.
`Channel#thread`
=> feat: message threads

lib/discordrb/api/interaction.rb, lib/discordrb/api/webhook.rb, lib/discordrb/data/interaction.rb, lib/discordrb/events/interactions.rb
Adds support for sending files (attachments) in interaction responses and closes out https://github.com/shardlab/discordrb/issues/227.
`attachments` KWARG to interaction response methods.
Something akin to this for most interaction response/webhook API calls.
```ruby
body = if attachments
files = [*0...attachments.size].zip(attachments).to_h
{ **files, payload_json: { type: type, data: body }.to_json }
else
{ type: type, data: body }.to_json
end
```
=> feat: attachments in interaction responses

lib/discordrb/bot.rb
Add support for passing in a custom integer value for Gateway intents.
in `calculate_intents`
```ruby
intents = [intents] unless intents.is_a? Array
```
=> Custom Intents

lib/discordrb/bot.rb, lib/discordrb/container.rb, lib/discordrb/events/channels.rb
Adds support for receiving and listening for the channel pins update gateway event.
`Discordrb::EventContainer#channel_pins_update`
`ChannelPinsUpdateEvent`
`ChannelPinsUpdateEventHandler`
=> feature: channel pins update event

.circleci/config.yml, .github/workflows/codeql.yml, .rubocop.yml, README.md, discordrb.gemspec
Since my previous attempt will most likely be superceded by another PR... 
Per [Ruby maintenance schedule](https://www.ruby-lang.org/en/downloads/branches/) version 3.1 is at its end of life, and should not be used. 
I've also bumped the version the Github workflows run on, since the version we're running is [deprecated](https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/).
Rubocop also requires minor change, since they have shifted over to a [plugin system](https://docs.rubocop.org/rubocop/plugin_migration_guide.html). If you attempt to run rubocop while developing DRB, the following warning is yielded:
```ruby
rubocop-performance extension supports plugin, specify `plugins: rubocop-performance` instead of `require: rubocop-performance` in …
```
=> Ruby 3.1 EOL & Workflows

discordrb-webhooks.gemspec
I forgot to bump the minimum ruby version for the webhooks client 
Minimum ruby version for the webhook client.
`3.1` --> `3.2`
=> Ruby Webhooks EOL Version Bump

lib/discordrb/api/server.rb, lib/discordrb/api/user.rb, lib/discordrb/bot.rb, lib/discordrb/data/member.rb, lib/discordrb/data/server.rb
In the past couple of months, I've noticed a few small bugs related to parsing emojis, removing timeouts so I thought I'd take a crack at fixing them.
When parsing an emoji that isn't accessible via `Bot#emoji`, we previously attempted to do this:
```ruby
{ 'animated' => !animated.nil? }
```
Which won't work properly, because animated will always be some kind of string never nil, as pointed out by @Dakurei [here on Discord](https://discord.com/channels/81384788765712384/381891448884428801/1276916192849956927).
--- 
When trying to change the bot's own nickname we use the `guilds/#{server_id}/members/@me/nick` endpoint. We should probably swap to `guilds/#{server_id}/members/@me`, since the latter is what Discord seems to prefer, shown by the [deprecation …
=> bugfixes: emoji parsing & removing timeouts

lib/discordrb/api/server.rb, lib/discordrb/data/member.rb
Add server avatar support.
Closes #145
---
- `MemberAttributes#avatar_id`
- `Member#avatar`
- `MemberAttributes#avatar_id` no longer delegates to `User` directly
- `Member#avatar` no longer delegated to `User` directly
=> feat: add server avatar

lib/discordrb/data/member.rb
Recently, we moved all of the logic for updating users from `GUILD_MEMBER_UPDATE` events into `Member#update_data`. Unfortunately, members on `MESSAGE_CREATE` events don't include a nested user, which causes things to immediately error out.
User serialization on `Member#update_data`
=> fix: broken members on MESSAGE_CREATE due to recent changes

lib/discordrb/data/server.rb
Guilds received from [:GUILD_CREATE](https://discord.com/developers/docs/events/gateway-events#guild-create-guild-create-extra-fields) events include an extra `threads` field containing all the active threads in the guild. I think we should probably cache these, so I added in a method that caches them
=> cache active threads on GUILD_CREATE events

lib/discordrb/bot.rb
This PR fixes an issue where registering application command event handlers and a raw event handler would cause errors like these:
```ruby
#<Thread:0x0000000145776960 /opt/homebrew/lib/ruby/gems/3.4.0/bundler/gems/discordrb-74d6415c6e15/lib/discordrb/bot.rb:1574 run> terminated with exception (report_on_exception is true):
/opt/homebrew/lib/ruby/gems/3.4.0/bundler/gems/discordrb-74d6415c6e15/lib/discordrb/bot.rb:1575:in 'block in Discordrb::Bot#handle_dispatch': undefined method 'interaction' for an instance of Discordrb::Events::RawEvent (NoMethodError)
Thread.current[:discordrb_name] = "it-#{event.interaction.id}"
``` 
Now please hear me out, but the fix to this was actually changing the name of `event` to `cmd_event`.
Application commands execute asynchronously within a thread, which …
=> fix: allow raw and application command event handlers to co-exist

lib/discordrb/bot.rb, lib/discordrb/container.rb, lib/discordrb/data/message.rb, lib/discordrb/data/server.rb, lib/discordrb/events/members.rb, lib/discordrb/events/message.rb, lib/discordrb/events/threads.rb, spec/bot_spec.rb, spec/data/message_spec.rb, spec/event_spec.rb
Currently, we makes an HTTP request for any server member that isn't cached. The main causes of these network requests are `MESSAGE_CREATE` and `GUILD_MEMBER_UPDATE` events. This PR attempts to make members in many of the more spammy events be lazily cached.
In the future we should probably revisit this and automatically request member chunks on `GUILD_CREATE`
- Made `Message#author` be lazily resolved (from Swarley)
- Don't request un-cached members on `GUILD_MEMBER_UPDATE`
- Attempt to update cached members with member objects from `MESSAGE_CREATE` at the dispatch level
- Make server members in `THREAD_MEMBERS_UPDATE` be lazily resolved
- Cache full member objects on `MESSAGE_REACTION_ADD`
=> fix: lazily cache un-cached members

lib/discordrb/api/server.rb, lib/discordrb/data/role.rb, lib/discordrb/data/server.rb, spec/json_examples/role.json
This PR adds support for gradient roles.
`Role#tertiary_colour`
`Role#tertiary_colour=`
`Role#secondary_colour`
`Role#secondary_colour=`
`Role#gradient?`
`Role#holographic?`
`Role#update_colours`
`tertiary_colour` and `secondary_colour` parameter to `Server#create_role`
The `data['color']` field was deprecated by Discord, so now, all color related fields are fetched from `data['colors']`.
Passing an integer directly to `Role#colour=` is now supported. Previously, this setter only accepted an instance of `Discordrb::ColourRGB`.
`API::Server#update_role` Now entirely uses `:undef` in order to avoid having to serialize the `colours` hash on every API request.
Role data is now directly updated using the role object returned by Discord. Previously, `Role#update_data` would attempt to do some …
=> feat: gradient roles

examples/awaits.rb, examples/ping.rb, examples/ping_with_respond_time.rb, examples/select_menus.rb, examples/shutdown.rb, examples/webhooks.rb, lib/discordrb/api/channel.rb, lib/discordrb/bot.rb, lib/discordrb/data/channel.rb, lib/discordrb/data/message.rb, lib/discordrb/events/message.rb
This PR adds in a KWARG version of `Channel#send_message`. I went and updated all the examples as well, since it might be a good idea to point people to the new version of the method
`Channel#send_message!`
`enforce_nonce` parameter
`Respondable#send_message!`
Previously, there was a bug where directly creating a reply with a message ID would error out. The fix was to change the line below to use `#resolve_id` instead
**Broken**
```ruby
message_reference = { message_id: message_reference.id } if message_reference.respond_to?(:id)
```
**Fixed**
```ruby
message_reference = { message_id: message_reference.resolve_id } if message_reference.respond_to?(:resolve_id)
```
=> feat: Channel#send_message!

lib/discordrb.rb, lib/discordrb/api/server.rb, lib/discordrb/data/profile.rb, lib/discordrb/data/server.rb, lib/discordrb/data/webhook.rb, spec/data/webhook_spec.rb
A few months ago in November, we [discussed](<https://discord.com/channels/81384788765712384/381891448884428801/1301199422444666922>) adding a Base64 encoding helper. This adds that, since base64 encoding is also required for a bunch of things that we don't support yet
`Discordrb.encode64`
=> feat: base64 encoder

lib/discordrb/api/channel.rb, lib/discordrb/data/channel.rb
This PR adds support for creating forum posts. This is pretty similar to creating a normal message, except you can specify tags on the forum post and pass an audit log reason as well.
=> feat: allow creation of forum posts

lib/discordrb/data/message.rb
This PR adds the `Message#mentions?` method that can be used to check if a role or user was mentioned in a message. Additionally, I discovered one bug while adding this method:
```ruby
if @channel.text?
data['mention_roles']&.each do |element|
@role_mentions << @channel.server.role(element.to_i)
end
end
``` 
This is actually incorrect because role mentions can happen in places like threads, news channels, stage channels, etc. I didn't bother fixing the bug in this PR because there's already another PR which fixes it: https://github.com/shardlab/discordrb/pull/352
`Message#mentions?`
=> feat: Message#mentions?

lib/discordrb/container.rb, lib/discordrb/events/message.rb, spec/event_spec.rb
All of our message events except `message_delete` support accessing `#server` directly. I went and added `#server` on `MessageIDEvent` since it might be good to have consistent attributes on similar events, but it's understandable if this is not something that should be done.
=> feat: add server attribute to MESSAGE_DELETE

lib/discordrb/bot.rb
Discord has a [USER_UPDATE](https://discord.com/developers/docs/events/gateway-events#user-update) event which is fired whenever info about the bot's current user changes. You'd think that we'd already be covered by the `:GUILD_MEMBER_UPDATE` event for this case, but I've noticed that `:GUILD_MEMBER_UPDATE` doesn't fire whenever properties about the current bot change without the `:server_members` intent.
```ruby
when :USER_UPDATE
@profile = Profile.new(data, self)
```
=> feat: handle USER_UPDATE events

lib/discordrb/data/server.rb
I think `GUILD_UPDATE` is fired whenever someone boosts a server, or it loses a boost. Unfortunately, I don't think we have anything that updates this in the cache, which is what's probably causing the cache to become stale.
- So while I was going through the initializer, I saw that we actually double cache channels on `:GUILD_CREATE`. This is because the initializer called `#process_channels` and then `#update_data` would also call that method again. I think it's safe to say that we probably only should call this once.
- Another thing is that the server's owner can change, and bots will get a `:GUILD_UPDATE` when that happens. Unfortunately, this means we can't memoize the owner, since there's a possibility that the memoized owner isn't the same as the `@owner_id` variable. I learned …
=> fix: server boost caching
